KhronosGroup/OpenCL-Headers

cl_ext_intel.h

This pull request contains header updates for two recently posted Intel extensions:
- cl_intel_planar_yuv
- cl_intel_device_side_avc_motion_estimation

header updates for Intel extensions

---

CL/cl_ext.h

Add enums for cl_arm_get_core_id

---

CL/cl_ext.h

Add definitions for cl_arm_job_slot_selection

---

CL/cl_ext.h

Add definitions for cl_arm_import_memory_android_hardware_buffer

---

.travis.yml
tests/CMakeLists.txt
tests/README.md
tests/test_cl.h.c
tests/test_cl_egl.h.c
tests/test_cl_ext.h.c
tests/test_cl_ext_intel.h.c
tests/test_cl_gl.h.c
tests/test_cl_gl_ext.h.c
tests/test_cl_icd.h.c
tests/test_cl_platform.h.c
tests/test_cl_version.h.c
tests/test_headers.c
tests/test_opencl.h.c

The tests are copied from OpenCL-CTS. A small amount of additional CMake work will be needed to test on Windows as well.
Contributes to #58.

Add tests and Travis CI config

---

CL/cl_ext.h

Add CL_IMPORT_DMA_BUF_DATA_CONSISTENCY_WITH_HOST_ARM definition

---

CL/cl.h

Fixes #67.
I will also create an OpenCL-Docs PR to fix the XML file.

move subgroup queries from cl_kernel_info to cl_kernel_sub_group_info

---

CL/cl.h

Corresponding XML file PR is here:
https://github.com/KhronosGroup/OpenCL-Docs/pull/225

add experimental enum CL_COMMAND_SVM_MIGRATE_MEM

---

CL/cl.h

Corresponding XML file PR is here:
https://github.com/KhronosGroup/OpenCL-Docs/pull/226

experimental enums for language queries

---

CL/cl_ext.h

Add cl_khr_extended_versioning macro

---

.travis.yml
tests/CMakeLists.txt

Fixes #80
Signed-off-by: Kévin Petit <kpet@free.fr>

Add Windows CI using Travis

---

CL/cl_ext.h

add tokens for cl_amd_device_attribute_query

---

CL/cl_ext.h

Signed-off-by: Einar Hov <einar.hov@arm.com>

Add cl_khr_device_uuid definitions

---

CL/cl_ext.h

Specification in https://github.com/KhronosGroup/OpenCL-Docs/pull/423
Signed-off-by: Plamen Petkov <plamen.petkov@arm.com>

Add definitions for cl_arm_scheduling_controls

---

CL/cl_ext.h

Specification in https://github.com/KhronosGroup/OpenCL-Docs/pull/399

Add definitions for cl_ext_cxx_for_opencl

---

CL/cl_ext.h

Accompanies KhronosGroup/OpenCL-Docs#491

Added definitions for cl_img_mem_properties.

---

CL/cl_platform.h

Integrity toolchain supports the attribute.

Use the alignment attribute under Integrity OS.

---

CL/cl_ext.h

Accompanies KhronosGroup/OpenCL-Docs#489

Added definitions for cl_img_generate_mipmap.

---

.github/workflows/cmake.yml

Update apt package list in CI before running cmake

---

CL/cl_ext.h

Signed-off-by: Oualid Khelifi <oualid.khelifi@arm.com>

Add definitions for cl_arm_scheduling_controls v0.2.0

---

CL/cl_platform.h

Signed-off-by: Kévin Petit <kevin.petit@arm.com>

Remove unused CL_EXTENSION_WEAK_LINK definition

---

CL/cl_ext.h

Signed-off-by: Neil Hickey <neil.hickey@arm.com>

Add definitions for cl_arm_scheduling_controls v0.3.0

---

CL/cl_ext.h

Add definitions for cl_arm_controlled_kernel_termination

---

CL/cl_ext.h

Signed-off-by: Einar Hov <einar.hov@arm.com>

Add definitions for cl_arm_import_memory_android_hardware_buffer v1.1.0

---

CL/cl_ext.h

Add new enums and functions for cl_khr_pci_bus_info and cl_khr_suggested_local_work_size.

add cl_khr_pci_bus_info and cl_khr_suggested_local_work_size

---

CL/cl_ext.h

Update headers for cl_khr_integer_dot_product.
See: https://github.com/KhronosGroup/OpenCL-Docs/pull/627

update headers for cl_khr_integer_dot_product

---

CL/cl_ext.h

Updates extension headers for cl_intel_device_attribute_query.
See: https://github.com/KhronosGroup/OpenCL-Docs/pull/657

update extension headers for cl_intel_device_attribute_query

---

CL/cl_ext.h

Specification: https://github.com/KhronosGroup/OpenCL-Docs/pull/727

Add definitions for cl_arm_protected_memory_allocation

---

CL/cl_ext.h

Adding macros for cl_intel_queue_no_sync_operations

Update cl_ext.h for cl_intel_queue_no_sync_operations

---

CL/cl_ext.h

Change-Id: Ic4d59b41e0c8198c8b3044fa7caad817eaf8bc59

Add definitions for cl_arm_scheduling_controls v0.5.0

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

See https://github.com/KhronosGroup/OpenCL-ICD-Loder/pull/198 .

Fix CI for MacOS

---

CL/cl_ext.h
scripts/cl_ext.h.mako

- Add cl_ext_image_raw10_raw12 definitions
- Remove CL_COMMAND_BUFFER_STATE_INVALID_KHR

Update extension headers

---

CL/cl_ext.h

Adds clReImportSemaphoreSyncFd API call
Added token for CL_SEMAPHORE_EXPORTABLE_KHR query

updates extension headers for the latest XML file

---

CL/cl_ext.h

Generated from cl.xml in https://github.com/KhronosGroup/OpenCL-Docs/pull/1338

Add definitions for cl_qcom_perf_hint
