KhronosGroup/OpenCL-Headers

cl_platform.h

_MSC_VER is undefined under MinGW. This tests for it.

Fix gcc -Wundef warning

---

cl_platform.h

Added missing cl_halfn declarations.
Certain devices are able to read/write or even perform math operations
on cl_halfn types.

cl_halfn declarations

---

cl_platform.h

I guess gcc in Ubuntu 14.04 does not define __GNUC__. Oh well.

Fix -Wundef warning under Ubuntu 14.04

---

CL/cl.h
CL/cl_ext.h

Currently, trying to query for double precision standards using `CL_DEVICE_DOUBLE_FP_CONFIG` on **OpenCL 1.1** or lower, throws an error saying "**_the macro is undeclared in this scope_**". Querying for `half` using `CL_DEVICE_HALF_FP_CONFIG` works fine, hence double should work as well. 
Furthermore, The **OpenCL 1.0** and **1.1** specification, in section **9.3.8**, also state that applications can query configuration information for devices that support double precision floating-point using the above macro.
The issue arises because `cl.h` defines the macro for `CL_VERSION_1_2` which means for **OpenCL 1.2** or greater. Then `cl_ext.h` states that the macro is already defined in `cl.h` and doesn't define it. This leaves out **OpenCL version 1.1** and **1.0**. Note that …

Fix for users trying to access CL_DEVICE_DOUBLE_FP_CONFIG on OpenCL 1.1 or lower

---

CL/cl.h
CL/cl_egl.h
CL/cl_ext.h
CL/cl_ext_intel.h
CL/cl_gl.h
CL/cl_gl_ext.h
CL/cl_platform.h
CL/opencl.h

These various deltas made it extremely difficult to work with non-Apple implementations of OpenCL on macOS. Apple always shipped their own versions of the headers anyway, and now that Apple have officially deprecated OpenCL on their platforms there is no reason to keep these deltas.
Fixes https://github.com/KhronosGroup/OpenCL-Headers/issues/31 as well as a few other unreported issues.
This probably needs some discussion before merging, potentially inside the OpenCL WG. In particular, if anyone has concerns that this might break their own workflows on macOS please let me know and we can discuss. Arguably I could have left the Apple extension declarations in `cl_ext.h` since they weren't causing problems, so I'm interested if people have thoughts on this.
@kpet Would be great if you could …

Remove all Apple specific content from headers

---

CL/cl.h
CL/cl_ext.h

This change adds KHR suffixed enums to cl_ext.h for the cl_khr_mipmap_image extension, and a comment describing why the un-suffixed enums in the main cl.h are incorrect (but are left for compatibility).
See:
https://github.com/KhronosGroup/OpenCL-Headers/issues/33#issuecomment-429996700

add suffixed enums for cl_khr_mipmap_image

---

CL/cl.h
CL/cl_dx9_media_sharing_intel.h
CL/cl_egl.h
CL/cl_ext.h
CL/cl_ext_intel.h
CL/cl_gl.h
CL/cl_gl_ext.h
CL/cl_va_api_media_sharing_intel.h

removed comments around arguments for CL.h
removed comments around arguments for cl_ext.h
removed comments around arguments for cl_ext_intel.h
removed comments around arguments for cl_dx9_media_sharing_intel.h
removed comments around arguments for cl_egl.h, cl_gl.h, and cl_gl_ext.h
removed comments around arguments for cl_va_api_media_sharing_intel.h
whitespace cleanup
Fixes #39.
Also fixes #37, since I was already modifying the file cl_gl_ext.h.

removing comments around arguments

---

CL/cl_platform.h

Currently, we add __attribute__((aligned(X))) for definitions like
cl_int, cl_short etc. This guarantees that the variable will be aligned
*at least* at an X byte boundary. We don't need to do this, for a few
reasons:
- Most of these types are fixed width (int32_t, int16_t, etc.). This
means __attribute((aligned(X))) isn't doing anything, as the types are
exactly the right size, so they will already be aligned to at least
their size. float and double are not guaranteed to be any given width,
though in practice they are almost always IEEE 754 floats and
therefore 4 and 8 bytes respectively. If they were not 4/8 bytes, it's
unclear that forcing 4/8 byte alignment would be good for either space
or performance efficiency.
- Attributes don't carry over to templates, which ends up causing a
GCC …

drop __attribute__((aligned(X))) from cl_X defs

---

CL/cl.h
CL/cl_ext.h

This is a partial fix for #42.
This change adds `KHR` suffixed enums for `cl_khr_imaged2d_from_buffer` to cl_ext.h.
It also moves the un-suffixed enums for `cl_khr_image2d_from_buffer` in cl.h to a section protected by `#ifdef CL_VERSION_2_0`, not `#ifdef CL_VERSION_1_2`, since the extension became a core feature in OpenCL 2.0.

added suffixed enums for cl_khr_image2d_from_buffer

---

CL/cl.h

As can be seen [here](https://github.com/KhronosGroup/OpenCL-Headers/blob/e986688daf750633898dfd3994e14a9e618f2aa5/opencl12/CL/cl.h#L102), the original OpenCL 1.2 headers, right before the unification, had the following definition for `cl_image_desc`:
```c
typedef struct _cl_image_desc {
cl_mem_object_type      image_type;
size_t                  image_width;
size_t                  image_height;
size_t                  image_depth;
size_t                  image_array_size;
size_t                  image_row_pitch;
size_t                  image_slice_pitch;
cl_uint                 num_mip_levels;
cl_uint                 num_samples;
cl_mem               buffer;
} cl_image_desc;
```
However, during the unification, the OpenCL 1.2 definition for `cl_image_desc` was changed according to …

Fix _cl_image_desc for OpenCL 1.2 compatibility

---

CL/cl_icd.h

...so that implementations (and others) can use definitions
straight from the headers instead of mirroring them.
The definitions come from https://github.com/KhronosGroup/OpenCL-ICD-Loader
with the following name changes:
- function pointers are now prefixed with 'cl_api_'
- the dispatch table type is now typedef'ed as 'cl_icd_dispatch', retaining
compatibility with `struct _cl_icd_dispatch`.
Contributes to https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/72

Add API function pointer and ICD dispatch table definitions

---

CL/cl_icd.h

This allows the `cl_icd.h` header to be included when `CL_TARGET_OPENCL_VERSION` is defined to something other than the most recent version.
The `#ifdefs` make it a bit messy. The APIs could be grouped by version to aid this. I didn't do this yet to keep things consistent with `cl.h` and also make this change easier to review.

Add version guards to ICD declarations

---

CL/cl.h

Represents a non-PCIe address `CL_DEVICE_VENDOR_ID` with the Khronos vendor ID.
Matching xml in https://github.com/KhronosGroup/OpenCL-Docs/pull/235

Experimental enum for Khronos vendor ID

---

CL/cl.h

Enum value depends on OpenCL spec change in https://github.com/KhronosGroup/OpenCL-Docs/pull/203
Including platform vendor IDs in the headers matches the convention of Vulkan, where this gets done automatically

Add enum value for `cl_khronos_vendor_id`

---

CL/cl.h
CL/cl_d3d10.h
CL/cl_d3d11.h
CL/cl_dx9_media_sharing.h
CL/cl_dx9_media_sharing_intel.h
CL/cl_egl.h
CL/cl_ext.h
CL/cl_ext_intel.h
CL/cl_gl.h
CL/cl_gl_ext.h
CL/cl_icd.h
CL/cl_platform.h
CL/cl_va_api_media_sharing_intel.h
CL/cl_version.h
CL/opencl.h
LICENSE

As agreed by the OpenCL WG on the 2020-03-17 teleconference.
I've preserved the additional copyright notices in the Intel extension headers where applicable. I've also removed some old SVN revision tags that are no longer relevant.
Fixes KhronosGroup/OpenCL-Headers#66.

Change license to Apache 2.0

---

CL/cl_ext.h

Fixes #69.
The corresponding XML change is here: https://github.com/KhronosGroup/OpenCL-Docs/pull/244

add missing error code CL_CONTEXT_TERMINATED_KHR

---

CL/cl_icd.h

Update included DirectX 10 header and include the DirectX sharing headers from CL/cl_icd.h.
This addresses #80 and is necessary to build clvk on Windows.

Make CL/cl_icd.h self-contained

---

CL/cl_ext_intel.h

Adds APIs and enums for the `cl_intel_unified_shared_memory` extension.  The draft extension spec can be found [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc).
Also, fixes a few other minor issues:
1. Updated copyright dates to 2020.
2. Removed extraneous semi-colons (supersedes #53).
3. Changed a few C++ comments (`//`) to C comments (`/* */`).

add APIs and enums for cl_intel_unified_shared_memory

---

CL/cl_platform.h

When using clang, altivec.h inclusion is taken care of by clang with -maltivec / -mno-altivec. Users shouldn't directly include it, it breaks compilation.

Fix build of dependent software with clang

---

CL/cl.h

This PR updates the query for device enqueue support from a boolean query to a bitfield capabilities query.
The corresponding changes to the XML file were made as part of this PR: https://github.com/KhronosGroup/OpenCL-Docs/pull/321

switch device enqueue boolean query to capabilities query

---

CL/cl.h
CL/cl_ext.h
CL/cl_ext_intel.h

Matching specification change made in https://github.com/KhronosGroup/OpenCL-Docs/pull/352

Introduce cl_properties type

---

CL/cl.h
CL/cl_icd.h

This PR contains three updates based on the latest OpenCL API changes.  I think it's easiest to review these as one PR, but I can separate them if desired:
1. Adds the `clSetContextDestructorCallback` API function (fixes #98)
2. Adds the `CL_DEVICE_LATEST_CONFORMANCE_PASSED` enum (fixes #99)
3. Deprecates the `clSetProgramReleaseCallback` API function (fixes #100)

update headers to latest OpenCL 3.0 API changes

---

CL/cl_ext_intel.h

- Add cl_intel_create_buffer_with_properties extension function
Spec: https://github.com/KhronosGroup/OpenCL-Docs/blob/master/extensions/cl_intel_create_buffer_with_properties.asciidoc
This extension allows OpenCL 1.x and 2.x devices to support the clCreateBufferWithProperties API that was added in OpenCL 3.0. This allows older OpenCL implementations to support other optional extensions or features that use the clCreateBufferWithProperties API to specify additional buffer properties, without recreating the API that is already part of OpenCL 3.0.
- Add CL_MEM_CHANNEL_INTEL property enum
Spec: https://github.com/KhronosGroup/OpenCL-Docs/blob/master/extensions/cl_intel_mem_channel_property.asciidoc
This extension allows programmers to request that a buffer allocation be implemented in a …

Add cl_intel_create_buffer_with_properties and cl_intel_mem_channel_property extensions

---

CL/cl_ext_intel.h

This PR adds the header changes for the `cl_intel_mem_force_host_memory` extension.
The spec PR with XML changes is here:
https://github.com/KhronosGroup/OpenCL-Docs/pull/446

header changes for cl_intel_mem_force_host_memory

---

CL/cl_ext_intel.h

The USM spec may be found here:
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc
Specifically, this PR adds the API for clMemBlockingFreeINTEL.

update APIs and enums for cl_intel_unified_shared_memory for rev Q

---

CL/cl.h
CL/cl_d3d10.h
CL/cl_d3d11.h
CL/cl_gl_ext.h
CL/cl_half.h
CL/cl_platform.h
tests/CMakeLists.txt

Avoid anon structs when MSVC uses /Za

---

CL/cl.h

This is a slight relaxation of the changes in #116 to re-enable anonymous unions by default (but not anonymous structs), and to disable anonymous unions only when they are known to not be supported, which is currently only for MSVC builds with `/Za`.
See also #121 
It's probably easiest to review these changes by [comparing against the previous commit](https://github.com/KhronosGroup/OpenCL-Headers/compare/9d17180a33566500551ff98e9eba62b0867a6f64...bashbaug:relax-anonymous-union) before #116.  The main difference is the addition of an `#ifdef` block to bypass the anonymous union for `/Za' builds.
This change passed all of my testing on Windows, including the tests I added in #123.

re-enable anonymous unions by default

---

CL/cl_version.h

Since OpenCL 3.0 is now final, we should switch the default OpenCL version for the headers if no OpenCL version is provided to OpenCL 3.0 instead of OpenCL 2.2.

switch the default version for the OpenCL headers to OpenCL 3.0

---

CL/cl_ext.h

Accompanies KhronosGroup/OpenCL-Docs#487.

Added missing define for cl_img_use_gralloc_ptr.

---

.github/workflows/cmake.yml
tests/test_headers.c

Fixes #132 
This PR fixes the printf format string warnings by using the `PRId64` and `PRIu64` format constants.  This is admittedly a little ugly but it seems to be the most portable way of printing a 64-bit integer, and it built and ran with no warnings or failures for me on Windows and Linux.
https://en.cppreference.com/w/cpp/header/cinttypes
Since the format string warnings are fixed I've also removed `-Wno-format` from the CI scripts.

fix printf format string warnings

---

tests/CMakeLists.txt
tests/test_cl_d3d10.h.c
tests/test_cl_d3d11.h.c
tests/test_cl_dx9_media_sharing.h.c
tests/test_cl_dx9_media_sharing_intel.h.c

Adds missing testing for cl_d3d10.h, cl_d3d11.h, and cl_dx9_media_sharing.h.

Add testing for cl_d3d10.h, cl_d3d11.h, and cl_dx9_media_sharing.h

---

CL/cl_gl.h
CL/cl_gl_ext.h

This PR moves the extension `cl_khr_gl_event` out of `cl_gl_ext.h` and into `cl_gl.h`.  Becuase there are no longer any extensions in `cl_gl_ext.h`, it also adds a build message instructing developers to include `cl_gl.h` directly instead of via `cl_gl_ext.h`.
Fixes #145.

move cl_khr_gl_event to cl_gl.h

---

CL/opencl.h

Since the extensions from `cl_gl_ext.h` have been moved into `cl_gl.h` (by https://github.com/KhronosGroup/OpenCL-Headers/pull/156) it should not longer be included from `opencl.h`.  This will eliminate a build message for applications that only include `opencl.h`.

do not include cl_gl_ext.h from opencl.h

---

README.md

Since commit 9fac4e9, OpenCL 3.0, not 2.2, has been the default version if CL_TARGET_OPENCL_VERSION is not defined. This updates the README accordingly.

Update default OpenCL version in README

---

CL/cl_ext.h

This PR contains the header changes for the `cl_intel_command_queue_families` extension.
See: https://github.com/KhronosGroup/OpenCL-Docs/pull/562

cl_intel_command_queue_families extension

---

CL/cl_d3d10.h
CL/cl_d3d11.h
CL/cl_dx9_media_sharing.h
CL/cl_egl.h
CL/cl_ext.h
CL/cl_gl.h
CL/cl_icd.h
CL/cl_layer.h
CL/cl_platform.h
CL/cl_va_api_media_sharing_intel.h

The macro `CL_API_ENTRY` is obviously intended for storage-class attributes, e.g. `__declspec(dllexport)`. Those attributes are not allowed in `typedef` declarations and will result in compilation errors. I have also submitted a [PR](https://github.com/KhronosGroup/OpenCL-Docs/pull/591) to fix the documentation.
Further `CL/cl_platform.h` contains changes to allow the macros `CL_API_ENTRY`, `CL_API_CALL` and `CL_CALLBACK` to be overridden externally.
Additionally `CL/cl_ext.h` contains fixes for the function declarations of extensions `cl_APPLE_SetMemObjectDestructor` and `cl_APPLE_ContextLoggingFunctions`.

Fixes for usage of macro CL_API_ENTRY

---

.github/workflows/cmake.yml

We need to update our CI configs to work with recent GitHub actions changes.
This PR disables the failing configs until we do this.  Specific changes in this PR are:
1. Use the Ubuntu 18.04 image instead of the Ubuntu 20.04 (ubuntu-latest) image.
2. Disable the gcc-8 config since it is no longer included in the Ubuntu 18.04 image.
2. Disable the MacOS Ninja config since the current method of installing it is no longer working.
If this PR is merged I'll create an issue to track re-enabling whichever configs we want to re-enable.

disable failing CI configs

---

CL/cl.h
CL/cl_platform.h

The header `CL/cl.h` is using `intptr_t`, but doesn't include the required `stdint.h` header.
On non-Windows platforms the header is already included by `CL/cl_platform.h`, but on Windows it causes a compilation error if `stdint.h` is not included before using `CL/cl.h`.

Add missing 'stdint.h' include to 'CL/cl.h'

---

CL/cl_d3d10.h
CL/cl_d3d11.h
CL/cl_dx9_media_sharing.h
CL/cl_ext.h
CL/cl_gl.h
CL/cl_va_api_media_sharing_intel.h

Updates headers for [cl_intel_sharing_format_query](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_sharing_format_query.html).

update extension headers for cl_intel_sharing_format_query

---

CL/cl_ext.h

cl_intel_exec_by_local_thread is the correct extension name.

Rename cl_intel_thread_local_exec to cl_intel_exec_by_local_thread

---

CL/cl_ext.h

Run `gen_headers.py` from https://github.com/KhronosGroup/OpenCL-Headers/pull/161 on XML file containing https://github.com/KhronosGroup/OpenCL-Docs/pull/711 new spec extensions.
The only XML changes are for the `cl_khr_command_buffer` extension, which declarations get generated at the top of `cl_ext.h` by the script. So I have taken the generated `cl_khr_command_buffer` code and applied it to the same location in master branch `cl_ext.h`.

Add provisional command-buffer extension

---

CL/cl_ext.h

Updates the headers for cl_intel_unified_shared_memory to be consistent with the latest spec.
Generated from the XML changes in: https://github.com/KhronosGroup/OpenCL-Docs/pull/709

update headers for cl_intel_unified_shared_memory

---

CL/cl_ext.h

This property allows user to specify which device global memory should be allocated to.
Supported by OpenCL 3.0 clCreateBufferWithProperties functions and OpenCL 1.x 2.x clCreateBufferWithPropertiesINTEL extension function.
Done to align with the spec in https://github.com/KhronosGroup/OpenCL-Docs/blob/master/extensions/cl_intel_mem_alloc_buffer_location.asciidoc
CC: @mkinsner @bashbaug @GarveyJoe

Add cl_intel_mem_alloc_buffer_location property

---

CMakeLists.txt

This PR follows the path paved by OpenCL-ICD-Loader crafted by @bashbaug [here](https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/117).
The behavior is:
- When built as top-level project
- Tests by default are built.
- To opt-out of testing, one uses the canonical `BUILD_TESTING` (on-by default)
- When built as a subproject
- Tests are _not_ built by default
- If tests are otherwise enabled (using the canonical `BUILD_TESTING` variable) one can opt-in to testing via `OPENCL_HEADERS_BUILD_TESTING`

Option to disable tests when subproject

---

CL/cl_ext.h

Generated from XML in https://github.com/KhronosGroup/OpenCL-Docs/pull/819, which introduces the `cl_khr_command_buffer_mutable_dispatch` extension, using generation script from PR https://github.com/KhronosGroup/OpenCL-Headers/pull/161

Definitions for cl_khr_command_buffer_mutable_dispatch

---

CL/cl_platform.h

I started compiling OpenCL-Layers on Windows using clang using both `clang-cl.exe` and `clang.exe`. When using the GNU-like CLI, it warns about anon-structs like GCC does too and the `__extension__` decorator is required.

Disable anon struct warnings for Clang on Win using GNU-like CLI

---

tests/test_headers.c

see discussion: https://github.com/KhronosGroup/OpenCL-SDK/issues/58#issuecomment-1260074680
This change uses the `cinttypes` header when compiling C++ tests rather than the  C-based `inttypes.h` header.  Some versions of the `inttypes.h` header require also defining `__STDC_FORMAT_MACROS` to use the printf format macro constants used in the tests with C++ compiles, but not all.  Switching to the `cinttypes` header seems to work in all cases.

use cinttypes instead of inttypes.h header for C++ tests

---

.github/workflows/linux.yml
.github/workflows/macos.yml
CMakeLists.txt
OpenCL-Headers.pc.in
cmake/JoinPaths.cmake

This adds support for pkg-config using two independent packages for OpenCL headers and loader library as discussed here https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/190
We may want to think about versioning here.

Added support for pkg-config.

---

CL/cl_layer.h

This is a pull request to add new info query to the cl_loader_layer `clGetLayerInfo` API.
This is a prerequisite of https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/175
and implements https://github.com/KhronosGroup/OpenCL-Docs/pull/851

cl_loader_layers update

---

.github/workflows/macos.yml

Looks like pkg-config is no longer available by default in the macos-11 image.  This PR checks to see if pkg-config is available and installs it if it isn't.  Needed to fix macOS CI.

install pkg-config if it is not already installed

---

.github/workflows/linux.yml
.github/workflows/macos.yml
CMakeLists.txt

Install pkgconfig file in CMAKE_INSTALL_DATADIR as headers are architecture independent.
This resolves issue https://github.com/KhronosGroup/OpenCL-Headers/issues/217
Once this is merged, the Loader CI will break, and I will make an accompanying pull request to resolve this as well.

Install pkgconfig file in CMAKE_INSTALL_DATADIR

---

CL/cl_ext.h

This is aligned with this Spec: https://github.com/KhronosGroup/OpenCL-Docs/pull/892. This extension supports SYCL hostpipes here: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_dataflow_pipes.asciidoc.
CC: @mkinsner @bashbaug @GarveyJoe

Add cl_intel_program_scope_host_pipe

---

CL/cl_ext.h

Define `0x1299` as `CL_COMMAND_BUFFER_CONTEXT_KHR` to reflect merged spec PR https://github.com/KhronosGroup/OpenCL-Docs/pull/899
See also original issue https://github.com/KhronosGroup/OpenCL-Docs/issues/898

Add enum for command-buffer context query

---

CL/cl_ext.h
scripts/cl_ext.h.mako

Adds support for the cl_khr_command_buffer_multi_device extension.
Generated from the XML file in https://github.com/KhronosGroup/OpenCL-Docs/pull/908.

add headers for cl_khr_command_buffer_multi_device

---

scripts/cl_ext.h.mako

The generated extension headers maintained an ordered list of older extensions to minimize diffs with the non-generated extension headers, but there is no reason to require this for new extensions.  If a new extension is not found in the list, sort it at the end automatically. Note, Khronos (KHR) extensions will also be sorted before multi-vendor (EXT) extensions, and before vendor extensions.

sort new extensions programmatically

---

CL/cl.h
CL/cl_ext.h
CL/cl_gl.h

Fixes #117.
This change corrects the OpenCL version for the `CL_DEPTH` enum.  `CL_DEPTH` was an extension until OpenCL 2.0, not OpenCL 1.2, so it shouldn't be in the core `cl.h` until OpenCL 2.0.
Also fixes the extension enums `CL_DEPTH_STENCIL` and `CL_UNORM_INT24`, which were never core enums and hence should not be in the core `cl.h` at all.
The extension header fixes were made by regenerating headers using the XML from https://github.com/KhronosGroup/OpenCL-Docs/pull/930, so this change should not be merged until the XML changes are merged.

fix the OpenCL version for the CL_DEPTH enum

---

CL/cl_ext.h

see: https://github.com/intel/compute-runtime/issues/677
Fixes the value of the enum CL_ME_SKIP_BLOCK_TYPE_8x8_INTEL from [cl_intel_advanced_motion_estimation](https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_advanced_motion_estimation.txt) to match the specification.
This is done by regenerating headers with the changes from https://github.com/KhronosGroup/OpenCL-Docs/pull/972.
Note that this PR only fixes this one issue and I have not fully regenerated the headers with the latest XML file, to simplify review and to avoid merge conflicts.

fix VME skip block type enum to match spec

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
README.md

Adds a short section to the README to describe the OpenCL headers compatibility policy.  In general, we will strive to maintain backward compatibility, but in rare cases we may break backward compatibility, especially for provisional features or extensions.
Also updates the CI scripts to skip GitHub actions if only README files are updated.

add compatibility notes

---

CL/cl_ext.h

adds clCommandSVMMemcpyKHR and clCommandSVMMemFillKHR

Update extension headers for OpenCL-Docs #915

---

CL/cl_ext.h

* Adds separate device handle lists for external memory and semaphores
* Adds bits for cl_khr_initialize_memory
* Adds enums for cl_arm_scheduling_controls
These header changes will require CTS changes because the device handle list changes are not backward compatible - see https://github.com/KhronosGroup/OpenCL-CTS/issues/1807.  If needed, I can separate the device handle list changes to their own PR.

updates extension headers for the latest XML file

---

CL/cl_ext.h

Created from https://github.com/KhronosGroup/OpenCL-Docs/pull/992 by running the `generate_headers` build target and taking only the related changes to `cl_ext.h`

Add cl_mutable_dispatch_asserts_khr definitions

---

CMakeLists.txt

Recent versions of CMake issue a deprecation warning:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Silence this warning by using a `...<max>` suffix
in `cmake_minimum_required` invocation.
No functional change intended.

Fix CMake deprecation warning

---

CL/cl_ext.h

Re-generates extension headers with the latest XML file.
Adds extensions:
* cl_khr_kernel_clock
* cl_img_cancel_command
Updates extension:
* cl_img_mem_properties
Adds an extension name define for many previously missing OpenCL C or SPIR-V-specific extensions.
Requesting a review from @paulfradgley for the IMG extensions specifically - thanks!

update extension headers with latest extensions

---

.github/workflows/presubmit.yml

The list of compilers/environments is explicit in the presubmit CI pipeline. Since the `-latest` GitHub runners are subject to periodic change, the matrix also needs to be updated from time to time.
An alternative would be to pin the jobs at specific runner versions, but since those versions cease to be supported over time, the porting of jobs to a new runner would be a larger monolithic task instead of the current gradual transition.
This PR fixes the following:
1. Fixed the path of `gcc-11` and `gcc-13` compiler in the `macos` jobs.
2. Removed compilation against the Visual C++ v141 toolset, which is no longer available in the `windows-latest` installation.

Update CI matrix

---

.github/workflows/presubmit.yml

- Addressed #254.
- Updated CI docker images from StreamHPC's to KhronosGroup's.
- Updated CI actions to use Node.js 20.

Fix CI failures

---

CL/cl_d3d10.h
CL/cl_d3d11.h
CL/cl_dx9_media_sharing.h
CL/cl_egl.h
CL/cl_ext.h
CL/cl_gl.h
CL/cl_layer.h
CL/cl_platform.h
CL/cl_va_api_media_sharing_intel.h

- Move CL/GL type declarations from cl_platform.h to cl_gl.h
- Include version macros for extensions

Update generated headers and remove CL/GL types from cl_platform.h

---

.github/workflows/presubmit.yml

On MacOS, CI is failing with: 
> Could not find compiler set in environment variable CC: gcc-11
I don't know if it is related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114007
Since gcc-11 has been disable for our other repositories, I don't think disabling it here is going to be a problem.

Disable gcc-11 on MacOS

---

CL/cl_ext.h

Proposal to pass the update configs to `clUpdateMutableCommandsKHR` as an array, rather than pointer changed linked list.
Generated from XML changes in https://github.com/KhronosGroup/OpenCL-Docs/pull/1045
See https://github.com/KhronosGroup/OpenCL-Docs/issues/1041 for motivation.
Related PRs:
* https://github.com/KhronosGroup/OpenCL-CTS/pull/1984
* https://github.com/KhronosGroup/OpenCL-CLHPP/pull/298

Use array for clUpdateMutableCommandsKHR

---

CL/cl_ext.h

Header changes to reflect XML changes from https://github.com/KhronosGroup/OpenCL-Docs/pull/1215 to address https://github.com/KhronosGroup/OpenCL-Docs/issues/1207
A new `cl_command_properties_khr` properties parameter is added to all command recording entry-points, and the patch version is bumped.

Add properties parameter to all command-buffer commands

---

CL/cl_ext.h

Update OpenCL headers by regenerating them from
latest XML files to include recent spec updates.

Update headers regenerated from latest xml

---

CL/cl_ext.h

Header update generated from OpenCL-Docs PR XML change https://github.com/KhronosGroup/OpenCL-Docs/pull/850

Command-buffer supported queue properties

---

CL/cl_ext.h

Generated from the XML changes in https://github.com/KhronosGroup/OpenCL-Docs/pull/1159
The changes to the cl_khr_command_buffer and cl_khr_command_buffer_multi_device extension versions is unrelated to cl_ext_buffer_device_address and only exist because we have not regenerated extension headers for the latest top-of-tree XML file.

headers for cl_ext_buffer_device_address

---

CL/cl_ext.h
README.md
scripts/cl_ext.h.mako
tests/CMakeLists.txt

fixes #247 
Wraps provisional extensions in an opt-in define so applications that do not use provisional extensions do not get broken by non-backwards compatible changes.
Notes:
* The define gets added automatically during header generation based on the `provisional="true"` line in the XML file.
* The define is currently an opt-in named `CL_PROVISIONAL_EXTENSIONS`, but it's trivial to change this if desired.
* Because it is an opt-in define, the current implementation does break backwards compatiblity, and applications using provisional extensions will need to add the opt-in define.
* We should consider how much additional testing we want to add (in this repo and in others) with this change.  For example, do we want to run some of the header tests with and without provisional extensions?

guard provisional extensions with an opt-in define

---

CL/cl_ext.h
README.md
scripts/cl_ext.h.mako
tests/CMakeLists.txt
tests/test_ext_headers.c

We want to leverage the mechanism for non-ratified extensions too. We cannot use the word provisional in that case as, according to the Khronos guidelines, it only applies to ratified extensions.
Change-Id: Ibb162050d7ad7b1a8f01fc5ef115d8952064e2da

Rename CL_ENABLE_PROVISIONAL_EXTENSIONS to CL_ENABLE_BETA_EXTENSIONS

---

CL/cl_ext.h
scripts/cl_ext.h.mako
scripts/gen/__init__.py

This implements in the headers https://github.com/KhronosGroup/OpenCL-Docs/pull/1005 which is discussed here https://github.com/KhronosGroup/OpenCL-Docs/issues/1003
Once this is merged, the loader PR https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/238 needs to be amended to remove duplication.

Implementation of cl_khr_icd 2.0.0

---

scripts/cl_ext.h.mako

Updates the extension header generation scripts to check for the newer "experimental" tag in addition to the prior "provisional" tag. Once usage of the "provisional" tag is phased out of the XML file, support for it can be removed from the header generation scripts, also.
see: https://github.com/KhronosGroup/OpenCL-Docs/pull/1383

add support for the experimental tag in the XML file

---

CL/cl_ext.h

Re-adds cl_khr_external_semaphore_dx_fence (beta)
* See: https://github.com/KhronosGroup/OpenCL-Docs/pull/1359
Updates cl_khr_kernel_clock (final)
* See: https://github.com/KhronosGroup/OpenCL-Docs/pull/1366

regenerate extension headers with the latest extensions
